# Generated by Django 5.2.7 on 2025-12-22 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeSimilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.IntegerField(default=0)),
                ('recipe_A', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_A', to='recipes.recipe')),
                ('recipe_B', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_B', to='recipes.recipe')),
            ],
            options={
                'ordering': ['-similarity_score'],
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='similar',
            field=models.ManyToManyField(blank=True, through='recipes.RecipeSimilar', to='recipes.recipe'),
        ),
        migrations.AddConstraint(
            model_name='recipesimilar',
            constraint=models.UniqueConstraint(fields=('recipe_A', 'recipe_B'), name='unique_similar_recipes'),
        ),
    ]
