# Generated by Django 5.2.7 on 2025-12-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell others about your cooking style, inspirations, or favourite flavours.', max_length=700),
        ),
        migrations.AddField(
            model_name='user',
            name='cooking_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('home_cook', 'Home Cook'), ('advanced', 'Advanced')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dietary_style',
            field=models.CharField(blank=True, choices=[('none', 'No specific diet'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('halal', 'Halal'), ('gluten_free', 'Gluten Free')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='favourite_cuisine',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
