# Generated by Django 5.2.7 on 2025-12-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipesimilar_recipe_similar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipesimilar',
            options={},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='similar',
            field=models.ManyToManyField(blank=True, related_name='similars', through='recipes.RecipeSimilar', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='recipesimilar',
            name='similarity_score',
            field=models.IntegerField(default=1),
        ),
    ]
