# Generated by Django 5.2.7 on 2025-12-24 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipesimilar_options_alter_recipe_similar_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipesimilar',
            name='unique_similar_recipes',
        ),
        migrations.AddField(
            model_name='recipesimilar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recipesimilar',
            name='recipe_A',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simsA', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='recipesimilar',
            name='recipe_B',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simsB', to='recipes.recipe'),
        ),
        migrations.AddConstraint(
            model_name='recipesimilar',
            constraint=models.UniqueConstraint(fields=('recipe_A', 'recipe_B'), name='unique_similarities'),
        ),
    ]
