# Generated by Django 5.2.7 on 2025-12-24 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_user_bio_user_cooking_level_user_dietary_style_and_more'),
        ('recipes', '0004_remove_recipesimilar_unique_similar_recipes_and_more'),
    ]

    operations = [
    ]
