# Generated by Django 5.2.7 on 2025-12-02 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        #('recipes', '0007_recipeview'),
        ('recipes', '0002_user_profile_image_recipe_recipeingredient_and_more'),
    ]

    operations = [
        #migrations.DeleteModel(
            #name='RecipeView',
        #),
    ]
