# Generated by Django 5.2.7 on 2025-12-02 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipeview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeView',
        ),
    ]
