# Generated by Django 4.2.26 on 2025-12-05 12:07
from django.db import models
from django.db import migrations
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_delete_recipeview'),
    ]

    operations = []


