# Generated by Django 5.2.7 on 2025-12-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipe_saved_by_delete_recipeview'),
    ]

    operations = [
        #migrations.DeleteModel(
        #    name='RecipeView',
        #),
    ]
