# Generated by Django 4.2.26 on 2025-12-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_delete_recipeview'),
    ]

    operations = []


