# Generated by Django 5.2.7 on 2025-12-03 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_delete_recipeview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeView',
        ),
    ]
